

Resources:

   ##Create the databases
  DBbook:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      AvailabilityZone: us-east-1a
      DBInstanceIdentifier: databasebook
      DBInstanceClass: db.t3.micro
      DBName: dbbook
      DBSubnetGroupName: 
        Ref: DBbookSubnetGroup
      Engine: mariadb
      VPCSecurityGroups:
        - Fn::ImportValue: !Sub "${aws-stack}-SGdb"
      MasterUsername: root
      MasterUserPassword: Test!2024

  ##Create the subnets
  DBbookSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnets about db
      DBSubnetGroupName: db-subnet-group-db
      SubnetIds:
        - Fn::ImportValue: !Sub "${aws-stack}-PrivateSubnetA"
        - Fn::ImportValue: !Sub "${aws-stack}-PrivateSubnetB"

Outputs:
  DBbook:
    Description: Database endpoint
    Value: !GetAtt DBbook.Endpoint.Address
